### ISSUE TITLE
Weird java crash with Neoforge on pack start

### ISSUE THREAD

**Issue by GordonHollow** [neoforged/NeoForge#1185]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.24

**Logs:** game not even create any logs

**Description of issue:**
```
Exception in thread "main" java.lang.module.ResolutionException: Module org.apache.logging.log4j.slf4j contains package org.apache.logging.slf4j, module org.apache.logging.log4j.slf4j2.impl exports package org.apache.logging.slf4j to org.apache.logging.log4j.slf4j
    at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
    at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:806)
    at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:754)
    at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
    at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
    at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
    at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:297)
    at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:196)
    at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
```
    
    have that error instantly when try to start any neoforge packs, it's just a text from console, game not even make any logs
    guess it's Java related, tried both Java 21 and 22 with same result(

**Comment by AterAnimAvis** [comment]
We don't provide support for TLauncher

**Comment by GordonHollow** [comment]
> We don't provide support for TLauncher

does it mean it's fully incompatible or just "go solve your problem yourself"?

**Comment by AterAnimAvis** [comment]
As in we personally won't provide Technical Support for TLauncher. Nor do we condone it's usage.
