### ISSUE TITLE
Improve error tracing on codec encoding failures for non-string keys

### ISSUE THREAD

**Issue by baileyholl** [neoforged/NeoForge#1251]
When a codec has a non-string key and is encoded to NBT or JSON, a generic error is thrown that mentions the keys value, but nothing about the codec or circumstances that triggered the failure. There is no mod to report to, and mods in dev have to use breakpoints to decipher what may have caused it.

Worst case this occurs with Itemstack#save. If a codec contains a non-string value, an error is thrown:
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-07-07 09:40:36
Description: Saving entity NBT

java.lang.IllegalStateException: some keys are not strings: [0]
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23118!/:?] {}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar%23118!/:?] {}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.ItemStack.save(ItemStack.java:418) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.player.Inventory.save(Inventory.java:414) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:mixin,re:classloading,pl:mixin:APP:curios.neoforge.mixins.json:MixinInventory from mod curios,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.player.Player.addAdditionalSaveData(Player.java:862) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin from mod ars_nouveau,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerPlayer.addAdditionalSaveData(ServerPlayer.java:402) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin from mod ars_nouveau,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:1799) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:curios.mixins.json:AccessorEntity from mod curios,pl:mixin:APP:ars_nouveau.mixins.json:rewind.RewindEntityMixin from mod ars_nouveau,pl:mixin:APP:ars_nouveau.mixins.json:light.LightEntityMixin from mod ars_nouveau,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedPlayerList.save(IntegratedPlayerList.java:32) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.players.PlayerList.saveAll(PlayerList.java:684) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:mixin,re:classloading,pl:mixin:APP:ars_nouveau.mixins.json:camera.PlayerListMixin from mod ars_nouveau,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.saveEverything(MinecraftServer.java:578) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.saveEverything(IntegratedServer.java:315) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:101) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:713) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[neoforge-21.0.52-beta.jar%23190!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {}
```

Reproduction:
```java
Map object type codec:
public record SlotMap(Map<Integer, String> slots) {

    public static final Codec<SlotMap> CODEC = Codec.unboundedMap(Codec.INT, Codec.STRING).xmap(SlotMap::new, SlotMap::slots);
}

Call encode:
CODEC.encodeStart(pLevelRegistryAccess.createSerializationContext(NbtOps.INSTANCE), this).getOrThrow();
```
This occurs inside `mergeToMap`. If we included a stringified tag in the stacktrace, we would know which mod or item is throwing the error. A message informing that only strings can be used as keys would help clarify during dev too.

```java
NbtOps#mergeToMap
    public DataResult<Tag> mergeToMap(Tag p_341945_, Map<Tag, Tag> p_341920_) {
        if (!(p_341945_ instanceof CompoundTag) && !(p_341945_ instanceof EndTag)) {
            return DataResult.error(() -> "mergeToMap called with not a map: " + p_341945_, p_341945_);
        } else {
            CompoundTag compoundtag = p_341945_ instanceof CompoundTag compoundtag1 ? compoundtag1.shallowCopy() : new CompoundTag();
            List<Tag> list = new ArrayList<>();

            for (Entry<Tag, Tag> entry : p_341920_.entrySet()) {
                Tag tag = entry.getKey();
                if (tag instanceof StringTag) {
                    compoundtag.put(tag.getAsString(), entry.getValue());
                } else {
                    list.add(tag);
                }
            }

            return !list.isEmpty() ? DataResult.error(() -> "some keys are not strings: " + list, compoundtag) : DataResult.success(compoundtag);
        }
    }
```

**Comment by Matyrobbrt** [comment]
The failing tag *is* included in the error message. In your case:
```
some keys are not strings: [0]
```
`0` is the tag that is not a string - it's a number.

In this case however the tag is a simple number so it's still hard to track where it came from. And while I do agree that it would be nice being able to know what codec caused this, it is impossible to have this information available. Therefore I am closing this issue.
