### ISSUE TITLE
Error: Picked up _JAVA_OPTIONS:  Exception in thread "main" java.lang.IllegalStateException

### ISSUE THREAD

**Issue by AleksTiGit** [neoforged/NeoForge#1282]
_When opening the version (with and without mods), Minecraft crashes and an error is displayed:_ 
`Picked up _JAVA_OPTIONS: 
Exception in thread "main" java.lang.IllegalStateException: Module named org.objectweb.asm.tree.analysis was already on the JVMs module path loaded from C:\Users\User\AppData\Roaming\.tlauncher\legacy\Minecraft\game\libraries\org\ow2\asm\asm-analysis\9.5\asm-analysis-9.5.jar but class-path contains it at location C:\Users\User\AppData\Roaming\.tlauncher\legacy\Minecraft\game\libraries\org\ow2\asm\asm-analysis\9.5@jar\asm-analysis-9.5@jar.jar
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:139)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
:`
_I use Legacy Launcher_

**Comment by HenryLoenwind** [comment]
tlauncher? So you're pirating the game?

**Comment by Technici4n** [comment]
We don't support tlauncher.
