### ISSUE TITLE
[1.21] An error occurred when run "/loot spawn <xyz> fish minecraft:gameplay/fishing/fish <xyz> minecraft:fishing_rod" command

### ISSUE THREAD

**Issue by SteveKunG** [neoforged/NeoForge#1328]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.98-beta

**Logs:**
```
[19:52:16] [Server thread/ERROR] [minecraft/Commands]: '/execute as SteveKunG at @s run loot spawn ~ ~1 ~ fish minecraft:gameplay/fishing/fish ~ ~ ~ minecraft:fishing_rod' threw an exception
java.lang.IllegalArgumentException: Missing required parameters: [<parameter minecraft:attacking_entity>]
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.storage.loot.LootParams$Builder.create(LootParams.java:133) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.commands.LootCommand.dropFishingLoot(LootCommand.java:429) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.commands.LootCommand.method_13205(LootCommand.java:87) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at MC-BOOTSTRAP/brigadier@1.2.9/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar%23148!/:?] {}
	at TRANSFORMER/minecraft@1.21/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:29) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:computing_frames,re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:computing_frames,re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.commands.execution.UnboundEntryAction.method_54405(UnboundEntryAction.java:8) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:computing_frames,re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:8) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:107) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.commands.Commands.executeCommandInContext(Commands.java:363) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.commands.Commands.performCommand(Commands.java:284) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:264) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.BaseCommandBlock.performCommand(BaseCommandBlock.java:131) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.block.CommandBlock.execute(CommandBlock.java:124) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.block.CommandBlock.tick(CommandBlock.java:102) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:730) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A,re:mixin,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:760) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:215) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:98) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:365) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:unprotect:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:267) ~[neoforge-21.0.98-beta-minecraft-merged-b898383154-1.21-loom.mappings.1_21.layered+hash.1839147940-v2-neoforge-21.0.98-beta.jar%23191!/:?] {re:mixin,pl:accesstransformer:B,pl:unprotect:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:unprotect:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
```

**Steps to Reproduce:**
 1. Simply run `/execute as @s at @s run loot spawn ~ ~1 ~ fish minecraft:gameplay/fishing/fish ~ ~ ~ minecraft:fishing_rod` command.
 2. An error occurred.

**Comment by HenryLoenwind** [comment]
That command does nothing for me in vanilla, and as executing invalid execute commands does nothing in vanilla, I'd say it is invalid.

Neo merely displays the error vanilla hides away; it is not causing it.

**Comment by 3TUSK** [comment]
> That command does nothing for me in vanilla

![image](https://github.com/user-attachments/assets/2e07e60b-0187-4c66-bb59-7669ac3a04fe)

The said command `/execute as @s at @s run loot spawn ~ ~1 ~ fish minecraft:gameplay/fishing/fish ~ ~ ~ minecraft:fishing_rod` works for me in *vanilla* 1.21, as shown above.

[`/loot` command is from vanilla game](https://minecraft.wiki/w/Commands/loot).

**Comment by Lolothepro** [comment]
I can confirm this bug

**Comment by shartte** [comment]
This is due to this patch:
<https://github.com/neoforged/NeoForge/blame/bfac3fb48dbd713610069370245805efdf6f14ad/patches/net/minecraft/world/level/storage/loot/parameters/LootContextParamSets.java.patch#L17>

In 1.20.1, this was `optional`:
https://github.com/neoforged/NeoForge/blob/1.20.1/patches/minecraft/net/minecraft/world/level/storage/loot/parameters/LootContextParamSets.java.patch#L15

`m_81408_` was `optional`
https://linkie.shedaniel.dev/mappings?namespace=mojang_srg&version=1.20.1&search=m_81408_&allowClasses=false&allowFields=false&translateMode=none&translateAs=yarn
