### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by MehanikTMYT** [neoforged/NeoForge#1351]
**Minecraft Version:** 1.21

**NeoForge Version:** neoforge-21.0.111-beta

**Logs:** 
[ERROR] SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
[ERROR] SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
[ERROR] Exception in thread "main"
[ERROR] java.lang.NoClassDefFoundError: com/google/common/collect/Streams
[ERROR] at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.util.ServiceLoaderUtil.loadServices(ServiceLoaderUtil.java:52)
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.moddiscovery.ModDiscoverer.<init>(ModDiscoverer.java:53)
[ERROR] at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.FMLLoader.beginModScan(FMLLoader.java:124)
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:84)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:97)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$7(TransformationServicesHandler.java:94)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	[ERROR] at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:96)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:50)
	[ERROR] at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:84)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
[ERROR] Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Streams
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 23 more	
**Steps to Reproduce:**
 just start
**Description of issue:**
errors in log file of launcher with libraries from official installer

**Comment by MehanikTMYT** [comment]
and error: java.util.ServiceConfigurationError: net.neoforged.neoforgespi.earlywindow.ImmediateWindowProvider: net.neoforged.fml.earlydisplay.DisplayWindow  which was fixed by changing fml.toml string: earlyWindowControl = false

**Comment by Technici4n** [comment]
We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [NeoForge Discord](https://discord.neoforged.net/). Ask in the `#user-support` channel (under the "For Users" category) in the Discord server instead.
