### ISSUE TITLE
Installer fails to run if on linux Wayland session

### ISSUE THREAD

**Issue by Int-Circuit** [neoforged/NeoForge#1533]
**Minecraft Version:** None

**NeoForge Version:** neoforge-21.1.50-installer

**Logs:** JVM info: Red Hat, Inc. - 21.0.4 - 21.0.4+7
java.net.preferIPv4Stack=true
Current Time: 11/09/2024 00:56:14
Host: maven.neoforged.net [195.181.170.19, 195.181.175.41, 37.19.194.81, 212.102.56.179, 169.150.255.183, 169.150.255.181]
Host: libraries.minecraft.net [13.107.246.42]
Host: launchermeta.mojang.com [13.107.246.42]
Host: piston-meta.mojang.com [13.107.246.42]
Host: sessionserver.mojang.com [13.107.246.42]
Found java version 21.0.4
Following redirect: https://neoforged.net/mirrorlist.json
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:164)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/java.awt.Frame.<init>(Frame.java:393)
	at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1925)
	at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:2001)
	at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:875)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:677)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:648)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:199)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:175)

**Steps to Reproduce:**
 1. Try to run installer by clicking it, doesn't run
 2. Run installer in terminal using java -jar neoforge-21.1.50-installer.jar
 3. Installer doesn't even install or propose install location for Neoforge. Get error log 

**Description of issue:**
When trying to install Neoforge using the latest installer on a wayland session (Fedora 40, up to date), installer fails both graphically and in CLI. Complains about "No X11 set DISPLAY variable". This could indicate that the installer doesn't correctly talks to Xwayland to draw the window. 

Since a lot of distro (Ubuntu, Fedora, Debian) are switching to Wayland as their default display server, I think that this bug is critical as the average user won't know what to do if their encounter this error.

**Comment by AterAnimAvis** [comment]
You likely don't have a full JRE/JDK installed, but a reduced "headless" variant.
