### ISSUE TITLE
Module named org.objectweb.asm.tree.analysis was already on the JVMs module path 

### ISSUE THREAD

**Issue by bonndan** [neoforged/NeoForge#1540]
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.51

**Logs:** 

This issues has also been reported on discord: https://discord.com/channels/313125603924639766/1249305774987939900/1284093357186088970

```
2024-09-13T16:57:07.708+0200 [ERROR] [system.err] Exception in thread "main" java.lang.IllegalStateException: Module named org.objectweb.asm.tree.analysis was already on the JVMs module path loaded from ...gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\9.7\e4a258b7eb96107106c0599f0061cfc1832fe07a\asm-analysis-9.7.jar but class-path contains it at location ....gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\9.5\490bacc77de7cbc0be1a30bb3471072d705be4a4\asm-analysis-9.5.jar
2024-09-13T16:57:07.708+0200 [ERROR] [system.err] 	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:139)
2024-09-13T16:57:07.709+0200 [ERROR] [system.err] 	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
```

**Steps to Reproduce:**
 1. Use the latest version 21.1.51
 2. runClient / runServer

**Description of issue:**

`cpw.mods.bootstraplauncher.BootstrapLauncher` throws an exception that as module named org.objectweb.asm.tree.analysis (9.7) was already on the JVMs module path 

`asm-analysis 9.5` is introduced by `net.neoforged:mergetool:2.0.3` e.g. in the step `neoGradleInternalUnhandledNeoFormMinecraftDependenciesForneoFormJoined1.21.1-20240808.144430` while all other parts depend on version 9.7

Even the latest versions of mergetool https://maven.neoforged.net/releases/net/neoforged/mergetool seem to depend on 9.5

There is an "ignoreList" system property used in BootstrapLauncher , but I dont know how to modify it.

**Comment by quat1024** [comment]
Latest working version of neoforge is `21.1.47` btw, for anyone else coming here from google. (because this info was buried in fucking discord)
