### ISSUE TITLE
[QoL Request] Optional Mods / Multi Mod problems

### ISSUE THREAD

**Issue by Speiger** [neoforged/NeoForge#159]
Some mods have multiple mods in them as a module type of system.
And to export a Mod you have to provide a mods.toml per mod that exists inside of them.

Yes i know you can merge mods into a single module but the opposite isn't possible.

Take scavenge for example, if I have a single development space for it and it's addons I have  to have:
- 1: File for the moddev space
- 2: X Amount of separate files PER MOD that i want to have inside my modding space, and when exporting i have to have a mapper that removes the "mods.toml" and replaces it with one of the other ones.   

It would nice if there was a better system regarding multi module mods where you could define mods as "Optional" and if the mod wasn't found inside of the class it would be simply discarded.

Also another issue is:
If a FAT mod was installed and you install a slim mod that just contains a single module forge/neoforge will simply crash.
It would be nice if a "simply do not load said mod/a proper user info" was thrown out.

To be honest, i don't see these issues as "unusable" but it would be nice if that would be addressed at some point, or at least a stance on it would be issued at some point.

**Comment by marchermans** [comment]
Hello, thanks for the request.

However we are having an issue understanding what exactly you are requested? What modules are you talking about? We normally talk about module layers, of which none exists that is named system...

Could you provide an example setup? Even if it does not compile/work? So that we can better figure out what you are requesting, and how to support it?

**Comment by Speiger** [comment]
@marchermans Lets take buildcraft as a example.

## FatMod Crash: 
They have a "Fat Jar" and "module jars", module jars being "energy/builders/robots" each being a separate jar.
If you try install a module jar next to a fat jar the game crashes without any actual ingame report what went wrong.

https://legacy.curseforge.com/minecraft/mc-mods/buildcraft
https://legacy.curseforge.com/minecraft/mc-mods/buildcraft-transport

Nowdays if you startup forge with duplicate mods or mods that have issues it will finish loading and then show you a screen: 
Ok this went wrong please fix it.
If a fat/multimod jar has a duplicate with a single mod jar the game just crashes,
yes the game crash log shows what went wrong but we know how good users are at reading those, otherwise the "what went wrong screen" wouldn't be necessary.

Edit: To clearify this a bit more. I am asking to improve the handling of issues with interactions between multimod jars and single mod jars.
Best solution is IMO, if a multimod jar mod has a single jar duplicate to either load the newer one, or if you can't "not load" the mod inside a multimod jar due to other issues simply not load single jar mod instead, or make a errored load that says: "What you are trying is not supported"

## Optional Mods

Basically the the mods.toml is really strict, where you have to either autogenerate it in the release builder if you have multiple mods in 1 workspace, or have multiple mods.toml files that you have to then maintain separately.

The request is to make the mods.toml less strict in the sense if a mod in said mods.toml wasn't found in the jar it will be ignored.
That way no "autogeneration script" or "multifile" solution is required.
Or provide a better approach.

Example is here what we have to do atm.
https://github.com/TinyModularThings/UniqueEnchantments/tree/1.19/src/main/resources/META-INF (Files)
https://github.com/TinyModularThings/UniqueEnchantments/blob/1.19/build.gradle#L127 (Custom build task that filters out the "mods.toml" and replaces it with the specific required "mods toml")


Edit: I hope this explains it better.

**Comment by Speiger** [comment]
@marchermans reminder that the info was provided.

**Comment by cech12** [comment]
@Speiger @marchermans 

I have an example mod, where I add an additional test mod in my development environment. In 1.20.2 it works, but in 1.20.4 I have issues to get the same structure running.
https://github.com/cech12/BucketLib

Maybe it helps to find & fix the issue. :)

**Comment by shartte** [comment]
> It would nice if there was a better system regarding multi module mods where you could define mods as "Optional" and if the mod wasn't found inside of the class it would be simply discarded.

We no longer require entrypoints to actually exist for a javafml mod. So I'd consider this complete.

**Comment by Speiger** [comment]
@shartte does that resolve the issue with the following scenario:
You have 2 mods:
- Mod A and Mod B.
You have 2 Jars.
- Jar 1: Contains Mod A & Mod B
- Jar 2: Contains Mod A

When you install both jars the modloader crashes, no user error visual just crash.

**Comment by AterAnimAvis** [comment]
If Jar 1 is including those mods as Jar-in-Jar, everything should just work.

**Comment by Speiger** [comment]
@AterAnimAvis no JIJ at play

**Comment by shartte** [comment]
> @shartte does that resolve the issue with the following scenario:
> You have 2 mods:
> - Mod A and Mod B.
> You have 2 Jars.
> - Jar 1: Contains Mod A & Mod B
> - Jar 2: Contains Mod A
> 
> When you install both jars the modloader crashes, no user error visual just crash.

Since you reported this as a feature request I tried to pick out of the original post what that feature was, and *that* has been implemented. Have you tried any of the other things you described with a recent neoforge version? There were major overhauls of the loader in the past 2 years. If there is still a scenario you think is a bug, please report that with a stack trace and we can take a look at that properly.

**Comment by Speiger** [comment]
@shartte i was able to reproduce it all the way to 1.21.3 reliabely. Haven't tried further due to IRL taking over everything.

**Comment by AterAnimAvis** [comment]
> [@AterAnimAvis](https://github.com/AterAnimAvis) no JIJ at play

And that's your actual issue then here, your trying to bypass the systems we have in place to do this kinda thing.
Jar-in-Jar is designed to handle this use case.
Jar 1 *should be* shipping the "module" mods via jar-in-jar.
This then allows for each individual "module" jar (i.e. Jar 2) to override the jij'd version in the "fat" jar (Jar 1).

The way your currently trying to do this is breaking JPMS and isn't a design we're going to support.

**Comment by Speiger** [comment]
@AterAnimAvis but the modloader shouldn't break. It should simply say to the user: "You have duplicated mod in an unresolving system please take either jarX or jarY out".
Thats all i am asking. So the user is at least getting some useful information out.
Because atm it is just crashing with a huge crashlog that isn't readable to the user at all.
I am not asking to make the situation work just not to break in an unusable way...

JIJ doesn't have to be the answer to something that the modloader can process before the first class even gets loaded...
Why were mods.toml introduced in the first place then if it can't handle this situation?

**Comment by shartte** [comment]
> [@shartte](https://github.com/shartte) i was able to reproduce it all the way to 1.21.3 reliabely. Haven't tried further due to IRL taking over everything.

Can you provide the actual stack trace you got out of it?

**Comment by Speiger** [comment]
@shartte here is the log. I can't atm recreate it in 1.21.3 because eclipse is being annoying atm (eclipse bug) and the latest build i have is for 1.21 atm...
But this is the with the latest 1.21 included.
```
ERROR: fml.modloading.duplicate_mod [testmod; TestModA-B.jar, TestModB.jar] 
[19:50:30.856] [main/ERROR] [loading.moddiscovery.ModDiscoverer/SCAN]: Failed to build unique mod list after mod discovery. net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- Mod testmod is present in multiple files: TestModA-B.jar, TestModB.jar

	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.UniqueModListBuilder.buildUniqueList(UniqueModListBuilder.java:85) ~[loader-4.0.23.jar%23170!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:87) ~[loader-4.0.23.jar%23170!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.FMLLoader.beginModScan(FMLLoader.java:125) ~[loader-4.0.23.jar%23170!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:84) ~[loader-4.0.23.jar%23170!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:97) ~[modlauncher-11.0.4.jar%23155!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$7(TransformationServicesHandler.java:94) ~[modlauncher-11.0.4.jar%23155!/:?] {}
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?] {}
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787) [?:?] {}
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?] {}
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?] {}
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) [?:?] {}
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) [?:?] {}
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) [?:?] {}
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) [?:?] {}
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) [?:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:96) [modlauncher-11.0.4.jar%23155!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:50) [modlauncher-11.0.4.jar%23155!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:84) [modlauncher-11.0.4.jar%23155!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23155!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23155!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23155!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-mmc5.jar:mmc5] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
```

Edit found more log...
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.util.NoSuchElementException: No value present
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 8 more
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at MC-BOOTSTRAP/fml_earlydisplay@4.0.23/net.neoforged.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:602)
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:94)
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.FMLLoader.beforeStart(FMLLoader.java:160)
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:115)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 17 more
Exiting with -1
```

**Comment by Speiger** [comment]
And the issue is the launcher just closes, it doesn't even display anything. Its as if you had a JVM crash...

**Comment by TelepathicGrunt** [comment]
> It should simply say to the user: "You have duplicated mod in an unresolving system please take either jarX or jarY out".

Your stacktrace says:

> Loading errors encountered: - Mod testmod is present in multiple files: TestModA-B.jar, TestModB.jar

This looks like exactly what you’re asking for. Mentions the issue is because the mod is in two existing jars already

Edit: this seems to be about the screen not showing up instead. Not the log stuff

**Comment by Speiger** [comment]
> This looks like exactly what you’re asking for. Mentions the issue is because the mod is in two existing jars already
> Edit: this seems to be about the screen not showing up instead. Not the log stuff

Yeah most users see only the game crashing and don't look at logs and simply are confused.
If the screen showed up and says: "You installed duplicated mods" that would remove a lot of bug reports being made.
