### ISSUE TITLE
bypass missing launcher profile error

### ISSUE THREAD

**Issue by ConStrum** [neoforged/NeoForge#1633]
Hello,

is there a way to install Neoforge into a folder without Minecraft launcher profiles, or to extract the required files directly from the installer to install them manually?

I would really appreciate if someone could help me with this.

Best regards

**Comment by ConStrum** [comment]
Here’s the English translation:

After experimenting a bit, I noticed the following issues:

After attempting to extract all files from the installer into a separate directory, an error occurs when trying to launch it.

The same error occurs when tricking the installer by using a self-created "launcher_profiles.json" file to install it into the custom directory.

The error in question appears as follows:

```
Exception in thread "main" java.lang.IllegalStateException: Duplicate key C:\Users\User\AppData\Local\MCULauncher\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.22.1\log4j-core-2.22.1.jar (attempted merging values EmbeddedFileSystemMetadata[path=C:\Users\User\AppData\Local\MCULauncher\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.22.1\log4j-core-2.22.1.jar, fs=C:\Users\User\AppData\Local\MCULauncher\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.22.1\log4j-core-2.22.1.jar, fsCh=sun.nio.ch.FileChannelImpl@25d250c6] and EmbeddedFileSystemMetadata[path=C:\Users\User\AppData\Local\MCULauncher\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.22.1\log4j-core-2.22.1.jar, fs=C:\Users\User\AppData\Local\MCULauncher\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.22.1\log4j-core-2.22.1.jar, fsCh=sun.nio.ch.FileChannelImpl@4df50bcc])
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:134)
        at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:135)
        at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:125)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.JarContentsImpl.<init>(JarContentsImpl.java:56)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.JarContentsBuilder.build(JarContentsBuilder.java:56)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.lambda$run$6(BootstrapLauncher.java:165)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:156)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
```

This error does not occur in the default Minecraft folder.

I’d really appreciate it if someone could help me resolve this issue.

Best regards

**Comment by AterAnimAvis** [comment]
We do not, and will not, provide support for development of 3rd Party Launchers
