### ISSUE TITLE
Can't use any of the run tasks inside MDK

### ISSUE THREAD

**Issue by FirEmerald** [neoforged/NeoForge#1664]
Minecraft Version: 1.21.3

NeoForge Version: 21.3.10-beta (latest 1.21.3 as of the time of issue creation)

Logs: (posting it here as it's short, trimming out standard gradle output)
```
> Task :runClient FAILED
Exception in thread "main" java.lang.IllegalStateException: Module named org.objectweb.asm.tree.analysis was already on the JVMs module path loaded from C:\Users\mccas\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\9.7\e4a258b7eb96107106c0599f0061cfc1832fe07a\asm-analysis-9.7.jar but class-path contains it at location C:\Users\mccas\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\9.5\490bacc77de7cbc0be1a30bb3471072d705be4a4\asm-analysis-9.5.jar
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:139)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
```

Steps to Reproduce:
1. create a project using NeoForge 21.3.10-beta
2. attempt to run the project using one of the neoforge runs under gradle tasks
3. the build fails

My NeoForge 1.21.3 project cannot be run from my IDE (Eclipse) due to what seems to be the same issue as #1540 
Is it possible the fix for that one didn't make it into the 1.21.3 builds?
Affected project: https://github.com/FirEmerald/AdditionalPlacements/tree/1.21.3-neoforge

**Comment by Matyrobbrt** [comment]
You'll need to update NeoGradle to latest. Additionally, the issue tracker is only for confirmed bugs, for future support please ask in our Discord server or on a discussion thread.

**Comment by FirEmerald** [comment]
I was pretty sure I was using the latest NeoGradle at the time. Additionally, the issue template said nothing about posting on the discord first.
I also strongly suggest against requiring an issue to be posted on discord first - anyone else with the same issue will **not** be able to find information about the issue when looking it up, which leads to frustration. Having the primary issue reporting location be something that shows up in a google search saves people time and effort.
