### ISSUE TITLE
Unable to launch server 1.20.1

### ISSUE THREAD

**Issue by kwaitsing** [neoforged/NeoForge#1684]
**Minecraft Version:** {Minecraft version}
1.20.1

**NeoForge Version:** {NeoForge version. *Version number, not latest/rb*}
1.20.1-47.1.5

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

```
tsingkwai@fedorax ~/t/server 🍬 sh run.sh 
Exception in thread "main" java.lang.IllegalStateException: Duplicate key /home/tsingkwai/tmp/server/libraries/net/neoforged/fancymodloader/loader/47.1.37/loader-47.1.37.jar (attempted merging values EmbeddedFileSystemMetadata[path=/home/tsingkwai/tmp/server/libraries/net/neoforged/fancymodloader/loader/47.1.37/loader-47.1.37.jar, fs=/home/tsingkwai/tmp/server/libraries/net/neoforged/fancymodloader/loader/47.1.37/loader-47.1.37.jar, fsCh=sun.nio.ch.FileChannelImpl@42d8062c] and EmbeddedFileSystemMetadata[path=/home/tsingkwai/tmp/server/libraries/net/neoforged/fancymodloader/loader/47.1.37/loader-47.1.37.jar, fs=/home/tsingkwai/tmp/server/libraries/net/neoforged/fancymodloader/loader/47.1.37/loader-47.1.37.jar, fsCh=sun.nio.ch.FileChannelImpl@6043cd28])
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:131)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:62)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:54)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.lambda$main$6(BootstrapLauncher.java:99)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:93)
```

**Steps to Reproduce:**
 1. Click Install Server
 2. sh run.sh

**Description of issue:**
Then it crashed

**Comment by TelepathicGrunt** [comment]
Just fyi, we recommend you to use Forge for 1.20.1 instead. It is more up-to-date on that mc version and Neoforge back then was trying to keep parity with forge but wasn't that great. Neoforge is better in 1.20.2 and newer as that is when we broke the parity. Closing this as we basically stopped supporting 1.20.1 Neoforge since it was more of a temporary thing for that version
