### ISSUE TITLE
Missing JavaFML

### ISSUE THREAD

**Issue by Sweek9** [neoforged/NeoForge#261]
!-- Thank you for reporting! −
^ Removed less/greater than symbols because they prevent the description from showing.

!-- For support with crashes and issues, please create a post on the forum instead: --
!-- https://www.minecraftforge.net/forum/forum/18-support-bug-reports/ --
^ Support/response is not needed (I can just switch back to Forge), and why would I report an issue with NeoForge to the Forge forum? The issue does not occur while using Forge, only NeoForge. I'll assume this message is out of date, carried over from the fork.

**Minecraft Version:** 
1.20.2

**NeoForge Version:** 
20.2.39-beta

**Logs:**
```
Picked up _JAVA_OPTIONS: 
[07:02:21] [main/INFO]: ModLauncher running: args [--username, {username}, --version, neoforge-20.2.39-beta, --gameDir, /Users/{username}/Library/Application Support/minecraft, --assetsDir, /Users/{username}/Library/Application Support/minecraft/assets, --assetIndex, 8, --uuid, ba9a8e5647e542069df6302b8cf8435c, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, , --xuid, , --userType, mojang, --versionType, release, --width, 1920, --height, 1080, --fml.neoForgeVersion, 20.2.39-beta, --fml.fmlVersion, 1.0.9, --fml.mcVersion, 1.20.2, --fml.neoFormVersion, 20231019.002635, --launchTarget, forgeclient]
[07:02:21] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8 by Microsoft; OS Mac OS X arch aarch64 version 14.1
[07:02:21] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[07:02:22] [main/INFO]: Trying GL version 4.1
[07:02:22] [main/INFO]: Requested GL version 4.1 got version 4.1
Failed to load NeoForged icon
[07:02:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/Users/{username}/Library/Application%20Support/minecraft/libraries/org/spongepowered/mixin/0.8.5@jar/mixin-0.8.5@jar.jar%23116!/ Service=ModLauncher Env=CLIENT
[07:02:22] [pool-2-thread-1/INFO]: GL info: Apple M1 Ultra GL version 4.1 Metal - 88, Apple
[07:02:22] [main/INFO]: Found mod file "{every mod}" of type MOD with provider {mods folder locator at /Users/{username}/Library/Application Support/minecraft/mods}
…(last line repeats for every mod, with {every mod} as the name and extension of the mod, and {username} representing my username)
[main/ERROR]: Missing language javafml version [48,) wanted by {every mod}
…(last line repeats for every mod, with {every mod} as the name and extension of the mod, and 48 sometimes being a lower number or *)
Exception in thread "main" java.lang.IllegalStateException: Failed to find system mod: minecraft
	at MC-BOOTSTRAP/fml_loader@1.0.9@jar/net.neoforged.fml.loading.ModSorter.detectSystemMods(ModSorter.java:178)
	at MC-BOOTSTRAP/fml_loader@1.0.9@jar/net.neoforged.fml.loading.ModSorter.buildUniqueList(ModSorter.java:142)
	at MC-BOOTSTRAP/fml_loader@1.0.9@jar/net.neoforged.fml.loading.ModSorter.sort(ModSorter.java:50)
	at MC-BOOTSTRAP/fml_loader@1.0.9@jar/net.neoforged.fml.loading.moddiscovery.ModValidator.stage2Validation(ModValidator.java:103)
	at MC-BOOTSTRAP/fml_loader@1.0.9@jar/net.neoforged.fml.loading.FMLLoader.completeScan(FMLLoader.java:163)
	at MC-BOOTSTRAP/fml_loader@1.0.9@jar/net.neoforged.fml.loading.FMLServiceProvider.completeScan(FMLServiceProvider.java:93)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.onCompleteScan(TransformationServiceDecorator.java:174)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$triggerScanCompletion$24(TransformationServicesHandler.java:145)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.triggerScanCompletion(TransformationServicesHandler.java:147)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:95)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

**Steps to Reproduce:**
 1. Install NeoForge.
 2. Drop Forge mod in mods folder. 
 3. Launch Minecraft w/ NeoForge version.

**Description of issue:**
Crash on launch.

**Comment by Technici4n** [comment]
This indicates that you have a mod with a dependency on FML version `[48,)` yet FML is currently at major version `1`. Most likely you installed some Forge-only mods, or some mods for an older version of Minecraft. Forge and NeoForge are not compatible anymore as of Minecraft 1.20.2.

**Comment by Sweek9** [comment]
Thanks for the info Technici4n. They are indeed Forge mods. I had expected they should work because the website says that NeoForge is compatible with Forge mods, and many of the mods I got on CurseForge do still say they support the Forge and NeoForge mod loaders simultaneously. Although it looks like development for NeoForge is on the rise, <1% of the mods I'm using have NeoForge specific versions. So I suppose I'll have to stick to Forge for now.
