### ISSUE TITLE
Error Minecraft 1.20.2 Neoforge

### ISSUE THREAD

**Issue by gameplayoffert** [neoforged/NeoForge#374]
**Minecraft Version:** 1.20.2

**NeoForge Version:** 20.2.86

**Logs**
```
Picked up _JAVA_OPTIONS: 
Exception in thread "main" java.lang.module.ResolutionException: Module com.github.oshi reads more than one module named cpw.mods.securejarhandler
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:722)
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:129)
```

**Steps to Reproduce:**
 1. install 1.20.2
 2. install neoforge 20.2.86
 3. run neoforge inside a launcher

**Description of issue:**
I have no mods, i use java 17, so i think that problem is probably coming from NeoForge. I don't have this problem when i run the vanilla version of minecraft or when i run the Forge version of minecraft, that happen only with "NeoForge"

**Comment by gameplayoffert** [comment]
I re-checked the rules about posting an issue here and the crashs are not allowed. I'm really sorry about that so this is why i'm closing this issue.
