### ISSUE TITLE
Server Failure to Start - Duplicate key

### ISSUE THREAD

**Issue by AzureDoom** [neoforged/NeoForge#38]
**Minecraft Version:** 1.20.1

**Neo Forge Version:** forge-1.20.1-47.1.28-installer

**Logs:** Installer log: https://gist.github.com/AzureDoom/fd41749aca4121c446f18056dcb90c6c

**Steps to Reproduce:**
 1. Run installer
 2. Extract server files to new folder
 3. Try and Start server

**Description of issue:**
Trying to launch server files (run.bat ) gives: 
```
Exception in thread "main" java.lang.IllegalStateException: Duplicate key C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar (attempted merging values EmbeddedFileSystemMetadata[path=C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar, fs=C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar, fsCh=sun.nio.ch.FileChannelImpl@38bc8ab5] and EmbeddedFileSystemMetadata[path=C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar, fs=C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar, fsCh=sun.nio.ch.FileChannelImpl@687080dc])
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:131)
        at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
        at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:62)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:54)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.lambda$main$6(BootstrapLauncher.java:99)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:93)
```

**Comment by AzureDoom** [comment]
Any updates on this? I see someone did a PR to fix, but it still needs to be reviewed by the looks. The lack of server support is something that is holding me back from porting any more of my mods over, as most of my users want them for Multiplayer use.

**Comment by sciwhiz12** [comment]
The linked PR is almost complete, but a bug in FancyModLoader causes the dedicated server to crash on load on Microsoft Windows. I've made a PR in FML to fix the bug, and once that's merged, the linked PR will be updated to bump the FML version accordingly, ~~and then reviewed and merged in short order~~.
