### ISSUE TITLE
Wayland: The platform does not provide the window position

### ISSUE THREAD

**Issue by gravit0** [neoforged/NeoForge#393]
**Minecraft Version:** 1.20.2

**NeoForge Version:** 20.2.86

**Logs:**
```
java.lang.IllegalStateException: GLFW error before init: [0x1000C]Wayland: The platform does not provide the window position
	at com.mojang.blaze3d.platform.GLX.lambda$_initGlfw$0(GLX.java:67) ~[client-1.20.2-20231019.002635-srg.jar%23189!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.checkGlfwError(Window.java:129) ~[client-1.20.2-20231019.002635-srg.jar%23189!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:66) ~[client-1.20.2-20231019.002635-srg.jar%23189!/:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:559) ~[client-1.20.2-20231019.002635-srg.jar%23189!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:454) ~[client-1.20.2-20231019.002635-srg.jar%23189!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:195) ~[client-1.20.2-20231019.002635-srg.jar%23189!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-1.0.16.jar%23172!/:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-1.0.16.jar%23172!/:1.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-1.0.16.jar%23172!/:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-1.0.16.jar%23172!/:1.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23147!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23147!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23147!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23147!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23147!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23147!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23147!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```
**Steps to Reproduce:**
 1. Use Wayland
 2. Set property `-Dorg.lwjgl.glfw.libname=PATH_TO_LIBGLFW_WAYLAND`
 3. Run NeoForge

**Description of issue:**
This error exclusive for Forge. Vanilla and Fabric don't have this error

**Comment by sciwhiz12** [comment]
Some quick searches leads me to PrismLauncher/PrismLauncher#1876, which links to https://github.com/Admicos/minecraft-wayland. According to that repository's README, you may need to disable the early loading window (by setting `earlyWindowControl` in the FML config file to `false`) for NeoForge to work properly under Wayland. I suggest you also take a look at the other contents of the repository, since it may be of interest to you.

Someone running Linux and Wayland will have to verify and debug this issue.

**Comment by gravit0** [comment]
Of course I know about this repository. Unfortunately `-Dfml.earlyprogresswindow=false` and `earlyWindowControl = false` did not help

**Comment by tmvkrpxl0** [comment]
For me, `-Dorg.lwjgl.glfw.libname` crashes immediately on startup with GLFW issue.
If I disable early progress window, it runs for a bit longer and crashes with other exception, also from GLFW.

**Comment by tmvkrpxl0** [comment]
Would you like to have my system information as well?

**Comment by tmvkrpxl0** [comment]
> For me, `-Dorg.lwjgl.glfw.libname` crashes immediately on startup with GLFW issue. If I disable early progress window, it runs for a bit longer and crashes with other exception, also from GLFW.

Reason for 2nd crash was I had was GLFW I'm using is too old for Minecraft. GLFW that Minecraft uses is 3.4, It is not yet released on my disto yet and I assume same goes for all debian based ones as well since 3.4 is released Feb 24.
so I had to built it locally. For testing I only enabled wayland support. and launched minecraft as described.

It was unable to create window, but after I set `__GL_THREADED_OPTIMIZATIONS=0` it launched fine with and without early window control.
I have verified that it is indeed using wayland as program icon was wayland logo instead of x11 logo.
@gravit0 Would you like to check it again?

**Comment by tmvkrpxl0** [comment]
Huh I discovered the same problem on 1.20.1
I was initially testing on 1.20.4 so I didn't see the issue.

**Comment by tmvkrpxl0** [comment]
On 1.20.1 You need to patch glfw somehow.
Both GLFW 3.3 and 3.4 throw error when application requests window position or changes icon, which are both unavailable on wayland for the moment.
Neoforge requests window position when early window control is enabled.
Minecraft 1.20.1 changes icon.
I think 1.20.4 detects wayland and avoids doing that both because 1.20.4 launched fine for me and the icon was still default wayland logo.

# Workaround
You need to build glfw yourself. The patch is not hard. Wayland functions for providing window position and changing icon both look like this:
```c
void _glfwGetWindowPosWayland(_GLFWwindow* window, int* xpos, int* ypos)
{
    // A Wayland client is not aware of its position, so just warn and leave it
    // as (0, 0)

    _glfwInputError(GLFW_FEATURE_UNAVAILABLE,
                    "Wayland: The platform does not provide the window position");
}
```
It just returns error immediately without doing anything.
As a workaround specifically for Minecraft, we can just change GLFW itself so that it doesn't even return error on those 2 cases.
1. Clone GLFW
2. open src/wl_window.c
3. Delete line that returns `_glfwInputError` on both `_glfwSetWindowIconWayland` and `_glfwGetWindowPosWayland`
4. create directory `build` under project root
5. run `cmake -S ./ -B ./build -D GLFW_BUILD_X11=0 -D BUILD_SHARED_LIBS=1`.
    * `-S ./` sets source of project to current directory, `-B ./build` sets build directory to `./build` which you just created, I disabled X11 support to ensure it actually uses wayland later, and build it as shared library because glfw is built as static library by default.
6. cd into `./build`
7. run `make`
    * now there's shared library at `glfw/build/src/libglfw.so`
8. launch minecraft with `__GL_THREADED_OPTIMIZATIONS=0` environment variable. Since `minecraft-launcher` was available on terminal for me I could just run `__GL_THREADED_OPTIMIZATIONS=0 minecraft-launcher`
    * This is crucial because concurrency is different on wayland and minecraft crashes with weird concurrency error.
9. specify library path with `-Dorg.lwjgl.glfw.libname` to that file in jvm argument in profile setting

**Comment by tmvkrpxl0** [comment]
Reason for disabling early window control being suggested is It makes minecraft not even call `_glfwGetWindowPosWayland`. But if you patch that as well just like I did You can leave it enabled.

**Comment by gravit0** [comment]
I have no way to test this now, but if you have the version after accepting https://github.com/neoforged/FancyModLoader/pull/68 the problem should go away
You can port this PR to older versions

**Comment by tmvkrpxl0** [comment]
there still maybe concurrency error (`__GL_THREADED_OPTIMIZATIONS=0`). I would have to test it myself

**Comment by tmvkrpxl0** [comment]
Do we still need this? NVIDIA explicit sink is now supported so we can just run it on x11.
Personally x11 experience is better for me now. fcitx5 didn't work on wayland.

**Comment by heipiao233** [comment]
在 2024年6月13日星期四 GMT+8 11:19:22，한현빈 写道：
> Do we still need this? NVIDIA explicit sink is now supported so we can just
> run it on x11. Personally x11 experience is better for me now. fcitx5
> didn't work on wayland.

As for me fcitx5 works better on Wayland than on X11.

**Comment by Erano01** [comment]
As suggested in [minecraft-wayland](https://github.com/Admicos/minecraft-wayland) repo and [PrismLauncher#1876](https://github.com/PrismLauncher/PrismLauncher/issues/1876), on Arch Linux with Wayland:

`find ~/.minecraft -name "fml.toml"`
`nano ~/.minecraft/config/fml.toml`
`earlyWindowControl = true → earlyWindowControl = false`
