### ISSUE TITLE
[1.20.1] Version Checker Error

### ISSUE THREAD

**Issue by UpcraftLP** [neoforged/NeoForge#497]
**Minecraft Version:** 1.20.1

**NeoForge Version:** 1.20.1-47.1.65

<Details>
<Summary>
Logs: (click to expand)
</Summary>
[08:54:13] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://maven.neoforged.net/releases/net/neoforged/forge/promotions_slim.json
[08:54:13] [Worker-Main-1/INFO] [minecraft/UnihexProvider]: Found unifont_all_no_pua-15.0.06.hex, loading
[08:54:16] [Forge Version Check/DEBUG] [ne.mi.fm.VersionChecker/]: [forge] Received version check data:
<html lang="en">
    <head>
      <meta charset="UTF-8" />
      <title>Reposilite - 404 Not Found</title>
    </head>
    <style>
      body {
        height: calc(100vh - 170px);
        display: flex;
        justify-content: center;
        align-items: center;
        font-family: Arial, Helvetica, sans-serif;
      }
    
      .error-view {
        text-align: center;
        width: 100vh;
        height: 100px;
      }
    
      .spooky p {
        margin-top: 0;
        margin-bottom: 0;
        font-size: 1.2rem;
        font-weight: lighter;
      }
      
      a:link, a:visited {
        color: rebeccapurple;
      }
    </style>
    <body>
      <div class='error-view'>
        <h1 style="font-size: 1.5rem">
          <span style="color: gray;">404︱</span>Resource not found
        </h1>
        <p><i>Cannot find net/neoforged/forge/promotionsslim.json in local and remote repositories</i></p>
        <p>Looking for a dashboard?</p>
        <div class="spooky">
          <p>{\__/}</p>
          <p>(●ᴗ●)</p>
          <p>( >🥕</p>
        </div>
        <p>Visit <a href="/#/releases/net/neoforged/forge/promotions_slim.json" style="color: rebeccapurple; text-decoration: none;">/#/releases/net/neoforged/forge/promotions_slim.json</a></p>
      </div>
    </body>
</html>
[08:54:16] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:1226) ~[gson-2.10.jar%23130!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar%23130!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.10.jar%23130!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:969) ~[gson-2.10.jar%23130!/:?] {}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[core-47.1.47.jar%23195!/:47.1] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) ~[core-47.1.47.jar%23195!/:47.1] {}
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.jar%23130!/:?] {}
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:182) ~[gson-2.10.jar%23130!/:?] {}
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144) ~[gson-2.10.jar%23130!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%23130!/:?] {}
	... 6 more
</Details>

**Description of issue:**

It appears that the file being accessed by the Version Checker on startup does not exist in the maven.

**Comment by MSandro** [comment]
is it possible to disable the version checker?
I have troubles to start a 1.20.4 Server with NeoForge!

**Comment by embeddedt** [comment]
This was fixed in https://github.com/neoforged/NeoForge/pull/567.
