### ISSUE TITLE
Double-Version at loading JAR-File server-1.20.4-1.20.4-20231207.154220-extra.jar

### ISSUE THREAD

**Issue by HellBz** [neoforged/NeoForge#651]
The Jar, what loaded while start the Server is not named Correctly.
Is right now started at **20.4.169**

server-1.20.4-1.20.4-20231207.154220-extra.jar
should named
server-1.20.4-20231207.154220-extra.jar

`[19:12:34.137] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.neoForgeVersion, 20.4.169, --fml.fmlVersion, 2.0.11, --fml.mcVersion, 1.20.4, --fml.neoFormVersion, 1.20.4-20231207.154220, nogui] 
[19:12:34.139] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 18.0.2.1 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0 
[19:12:34.201] [main/INFO] [loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver 
[19:12:34.226] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/GIT/forge-server-starter_old/test/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2379!/ Service=ModLauncher Env=SERVER 
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [libraries\net\minecraft\server\1.20.4-1.20.4-20231207.154220\server-1.20.4-1.20.4-20231207.154220-extra.jar]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.JarContentsImpl.<init>(JarContentsImpl.java:54)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.JarContentsBuilder.build(JarContentsBuilder.java:56)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.getMinecraftPaths(CommonServerLaunchHandler.java:42)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:37)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.FMLLoader.beginModScan(FMLLoader.java:155)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [libraries\net\minecraft\server\1.20.4-1.20.4-20231207.154220\server-1.20.4-1.20.4-20231207.154220-extra.jar]
	... 25 more[19:12:34.137] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.neoForgeVersion, 20.4.169, --fml.fmlVersion, 2.0.11, --fml.mcVersion, 1.20.4, --fml.neoFormVersion, 1.20.4-20231207.154220, nogui] 
[19:12:34.139] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 18.0.2.1 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0 
[19:12:34.201] [main/INFO] [loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver 
[19:12:34.226] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/GIT/forge-server-starter_old/test/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2379!/ Service=ModLauncher Env=SERVER 
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [libraries\net\minecraft\server\1.20.4-1.20.4-20231207.154220\server-1.20.4-1.20.4-20231207.154220-extra.jar]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.JarContentsImpl.<init>(JarContentsImpl.java:54)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.JarContentsBuilder.build(JarContentsBuilder.java:56)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.getMinecraftPaths(CommonServerLaunchHandler.java:42)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:37)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.FMLLoader.beginModScan(FMLLoader.java:155)
	at MC-BOOTSTRAP/fml_loader@2.0.11/net.neoforged.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [libraries\net\minecraft\server\1.20.4-1.20.4-20231207.154220\server-1.20.4-1.20.4-20231207.154220-extra.jar]
	... 25 more`

**Comment by AterAnimAvis** [comment]
Already confirmed. Originally brought up in [Discord](https://discord.com/channels/313125603924639766/852298000042164244/1210171437588021278)

The bump to the version of NeoGradle we use in `20.4.168` <https://github.com/neoforged/NeoForge/commit/64620154f763e447cea81735bac2ca431647034c>, brought in <https://github.com/neoforged/NeoGradle/pull/86> which had a regression in the format of the NeoForm version when we bake the [`args.txt`](<https://github.com/neoforged/NeoForge/blob/1.20.x/server_files/args.txt>). A fix is in progress.

**Comment by HellBz** [comment]
Change the Start-Arguments-TXT-File, works for now

**From:**
--fml.neoFormVersion 1.20.4-20231207.154220

**To:**
--fml.neoFormVersion 20231207.154220
