### ISSUE TITLE
Blockstate cache extensions cannot refer to NeoForge registries

### ISSUE THREAD

**Issue by embeddedt** [neoforged/NeoForge#667]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.182

**Description of issue:**

The new registry system appears to have made blockstate cache extensions which previously worked in 20.1 no longer work correctly in 20.4. Example of a crash (workspace is using Yarn mappings, but that is unrelated to the crash):

```
Caused by: java.lang.IllegalStateException: Registry not present for DeferredHolder{ResourceKey[neoforge:fluid_type / minecraft:empty]}: neoforge:fluid_type
	at net.neoforged.neoforge.registries.DeferredHolder.value(DeferredHolder.java:100) ~[neoforge-20.4.182-minecraft-merged-2de0ed56a8-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2-neoforge-20.4.182.jar%23174%23177!/:?] {re:classloading}
	at net.neoforged.neoforge.common.CommonHooks.getVanillaFluidType(CommonHooks.java:761) ~[neoforge-20.4.182-minecraft-merged-2de0ed56a8-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2-neoforge-20.4.182.jar%23174%23177!/:?] {re:classloading}
	at net.minecraft.fluid.Fluid.getFluidType(Fluid.java:107) ~[neoforge-20.4.182-minecraft-merged-2de0ed56a8-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2-neoforge-20.4.182.jar%23175!/:?] {re:classloading,pl:unprotect:A,re:mixin,pl:unprotect:A}
	at net.neoforged.neoforge.common.extensions.IFluidExtension.getAdjacentBlockPathType(IFluidExtension.java:122) ~[neoforge-20.4.182-minecraft-merged-2de0ed56a8-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2-neoforge-20.4.182.jar%23174%23177!/:?] {re:classloading}
	at net.neoforged.neoforge.common.extensions.IFluidStateExtension.getAdjacentBlockPathType(IFluidStateExtension.java:113) ~[neoforge-20.4.182-minecraft-merged-2de0ed56a8-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2-neoforge-20.4.182.jar%23174%23177!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.entity.ai.pathing.LandPathNodeMaker.getNodeTypeFromNeighbors(LandPathNodeMaker.java:483) ~[neoforge-20.4.182-minecraft-merged-2de0ed56a8-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2-neoforge-20.4.182.jar%23175!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:mixin:APP:lithium.mixins.json:ai.pathing.LandPathNodeMakerMixin,pl:mixin:A,pl:unprotect:A}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.handler$zza000$init(AbstractBlock.java:1000) ~[neoforge-20.4.182-minecraft-merged-2de0ed56a8-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2-neoforge-20.4.182.jar%23175!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:mixin:APP:lithium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.AbstractBlockStateMixin,pl:mixin:A,pl:unprotect:A}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.initShapeCache(AbstractBlock.java:520) ~[neoforge-20.4.182-minecraft-merged-2de0ed56a8-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2-neoforge-20.4.182.jar%23175!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:mixin:APP:lithium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.AbstractBlockStateMixin,pl:mixin:A,pl:unprotect:A}
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:7807) ~[neoforge-20.4.182-minecraft-merged-2de0ed56a8-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2-neoforge-20.4.182.jar%23175!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:unprotect:A}
```

The problem appears to be that vanilla blocks are registered and have their shape caches initialized before the fluid type registry is initialized and populated. As such, when the mixin indirectly attempts to access the fluid type of a fluid during `Blocks.<clinit>` it fails.

While this issue currently requires a mixin to reproduce, it's not implausible that Mojang code could end up triggering this bug down the road, so I believe it needs to be fixed. The same code worked without issues in 20.1.

There are a couple of ways I think this could be fixed. One would be to move bootstrapping of certain custom registries like fluid types to happen alongside vanilla bootstrap. Another would be to once again defer shape cache initialization for vanilla blocks till `BlockCallbacks.onBake`, but that will potentially introduce side effects. For instance, blockstates are not aware of their contained fluid state until the cache is initialized.

**Comment by Technici4n** [comment]
> One would be to move bootstrapping of certain custom registries like fluid types to happen alongside vanilla bootstrap.

This is not an option. Mods are only built after the bootstrap.

> Another would be to once again defer shape cache initialization for vanilla blocks till `BlockCallbacks.onBake`, but that will potentially introduce side effects. For instance, blockstates are not aware of their contained fluid state until the cache is initialized.

Yes, the side effect is problematic here.

If this happens with only NeoForge then we can try to find a solution. But otherwise, I don't think we need to worry about this issue. I would suggest that the offending mod be more careful with storing things in the block state cache.

**Comment by embeddedt** [comment]
Affected mods can work around this by mixing in their own cached fields to the `BlockState` itself and triggering initialization of them at the appropriate time. (For the record, this can actually be more efficient than piggybacking vanilla's cache, since the latter gets rebuilt whenever tags are reloaded, which is not needed as of 1.16.)
