### ISSUE TITLE
Guard recipe serializers against supplying null codecs

### ISSUE THREAD

**Issue by Shadows-of-Fire** [neoforged/NeoForge#693]
Returning null from `RecipeSerializer#codec()` produces a nonsensical gibberish error - we should validate them at registration time or shortly thereafter.

```
java.lang.NullPointerException: Cannot invoke "com.mojang.serialization.Decoder.decode(com.mojang.serialization.DynamicOps, Object)" because "c" is null
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$3(KeyDispatchCodec.java:72) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$4(KeyDispatchCodec.java:58) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-6.0.8.jar:?] {}
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-6.0.8.jar:?] {}
	at net.neoforged.neoforge.common.conditions.ConditionalOps$ConditionalDecoder.lambda$decode$9(ConditionalOps.java:205) ~[neoforge-20.4.194.jar:?] {re:classloading}
```

**Comment by Technici4n** [comment]
How did that even happen?

**Comment by Technici4n** [comment]
I don't think we want to be doing this for every method that returns a codec, so we should therefore not do it anywhere IMO. Feel free to reopen if you disagree. :D
