### ISSUE TITLE
NeoForge installer doesn't work

### ISSUE THREAD

**Issue by Trial97** [neoforged/NeoForge#740]
**Minecraft Version:** {Minecraft version}
1.20.1
**NeoForge Version:** {NeoForge version. *Version number, not latest/rb*}
47.1.81 and any version below
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
```
>java -jar forge-1.20.1-47.1.81-installer.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: no manifest section for signature file entry com/google/gson/internal/bind/JsonTreeWriter.class
	at java.base/sun.security.util.SignatureFileVerifier.verifySection(SignatureFileVerifier.java:630)
	at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:358)
	at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:289)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:283)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:239)
	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:761)
	at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1037)
	at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:72)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:883)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:848)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:794)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:689)
```
**Steps to Reproduce:**
 1. Download any jar version that is below 47.1.82 from the neoforge maven like:  https://maven.neoforged.net/releases/net/neoforged/forge/1.20.1-47.1.81/forge-1.20.1-47.1.81-installer.jar
 2. Try to run the installer
 3. Does not start

**Description of issue:**
The java version is:
```
> java --version
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7)
OpenJDK 64-Bit Server VM (build 17.0.10+7, mixed mode)
```

I tried reporting this on Discord but I got no answer:https://discord.com/channels/313125603924639766/313125603924639766/1221055556840722432

**Comment by Trial97** [comment]
After last update it looks like this works now
